pipeline {
  agent any

  environment {
    APP_DIR = 'water-source'
    APP_IMAGE = 'localhost:5001/water:ci'
  }

  stages {
    stage('Checkout') {
      steps {
        dir(env.APP_DIR) {
          git branch: 'main', url: 'https://github.com/turban-sizzle/fluffy-octo-sniffle.git'
        }
      }
    }

    stage('Tests Python 3.11') {
      agent {
        docker {
          image 'python:3.11'
          reuseNode true
        }
      }
      steps {
        dir(env.APP_DIR) {
          sh '''
            python --version
            pip install -r requirements.txt
            pytest --cov . --cov-report xml
          '''
        }
      }
    }

    stage('Build image') {
      steps {
        sh '''
          docker build \
            --file cicd/Dockerfile \
            --tag "$APP_IMAGE" \
            "$APP_DIR"
        '''
      }
    }

    stage('Push image') {
      steps {
        sh 'docker push "$APP_IMAGE"'
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: "${APP_DIR}/coverage.xml", allowEmptyArchive: true
    }
  }
}
